# Dataset reader arguments
dataset:
  image_features_train_h5: 'data/features_faster_rcnn_x101_train.h5'
  image_features_val_h5: 'data/features_faster_rcnn_x101_val.h5'
  image_features_test_h5: 'data/features_faster_rcnn_x101_test.h5'
  word_counts_json: 'data/visdial_1.0_word_counts_train.json'
  tokens_path: 'data/tokens.json'
  img_norm: 1
  concat_history: false
  max_sequence_length: 20
  vocab_min_count: 5


# Model related arguments
model:
  encoder: 'baseline_encoder_withP1'
  decoder: 'disc_by_round'

  img_feature_size: 2048
  word_embedding_size: 300
  lstm_hidden_size: 512
  lstm_num_layers: 2
  head_num: 3
  dropout: 0.4
  dropout_fc: 0.25


# Optimization related arguments
solver:
  batch_size: 12
  num_epochs: 3 # you can try more epochs or change the lr
  initial_lr: 0.002
  training_splits: "train"
  lr_gamma: 0.3
  lr_milestones:
    - 2
  warmup_factor: 0.5
  warmup_epochs: 0
